config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'home' => 'static_pages#home'

  get 'demo' => 'static_pages#demo'

  get 'about' => 'static_pages#about'

  resources :data_files, :only => [:index, :new, :create, :show, :destroy] do 
    collection { post :upload }
  end

  resources :folders, :only => [:index, :new, :create, :edit]

  resources :users, :only => [:new, :create, :show]

  resources :sessions, :only => [:new, :create, :destroy]

  get 'profile' => 'users#show'

  get 'upload' => 'upload#index'

  get 'signup' => 'users#new'

  post 'signup' => 'users#create'

  get 'login'  => 'sessions#new'

  post 'login'  => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  namespace :admin do
    resources :user_groups
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # 
  # Static home page
  #
  def home
  end

  # 
  # Static demo page
  #
  def demo
  end
  
  # 
  # Static about page
  #
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<div class = "row">
	<%= render 'layouts/buttons' %>
	<%= render 'layouts/folders' %>
	<%= render 'layouts/files' %>
</div>

app/views/static_pages/demo.html.erb
<% provide(:title, "Demo") %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="container">
  <% if logged_in? %>
    <%= render 'shared/main_grid' %>
  <% else %>
    <div class = "center">
    	<h1> fileio welcomes you to power up your enterprise with reliable and secure file storage. </h1>
    	<%= link_to "Login", login_path, class: "btn btn-lg btn-primary fileio-color" %>
    	<%= link_to "Signup", signup_path, class: "btn btn-lg btn-primary fileio-color" %>
    </div>
  <% end %>
</div>