config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'home' => 'static_pages#home'

  get 'demo' => 'static_pages#demo'

  get 'about' => 'static_pages#about'

  resources :data_files, :only => [:index, :new, :create, :show, :destroy] do 
    collection { post :upload }
  end

  resources :folders, :only => [:index, :new, :create, :edit]

  resources :users, :only => [:new, :create, :show]

  resources :sessions, :only => [:new, :create, :destroy]

  get 'profile' => 'users#show'

  get 'upload' => 'upload#index'

  get 'signup' => 'users#new'

  post 'signup' => 'users#create'

  get 'login'  => 'sessions#new'

  post 'login'  => 'sessions#create'

  get 'logout' => 'sessions#destroy'

  namespace :admin do
    resources :user_groups
  end
end

app/views/layouts/_buttons.html.erb
<div class = "row center">
Buttons will come here!
</div>

app/views/layouts/_files.html.erb
	
<div class="col-md-6 col-md-offset-0">
	<div class="collapse navbar-collapse" id="myNavbar">
		<ul class="nav navbar-nav">
			<li>
				<div class="dropdown">
					<button class="btn btn-primary dropdown-toggle" id="menu1" type="button" data-toggle="dropdown">+
						<span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
						<li role="presentation"><a role="menuitem" tabindex="-1" href="#">New Folder</a></li>
						<li role="presentation"><a role="menuitem" tabindex="-1" href="#">New File</a></li>
						<li role="presentation"><a role="menuitem" tabindex="-1" href="#">New Group</a></li>
						<li role="presentation" class="divider"></li>
						<li role="presentation"><a role="menuitem" tabindex="-1" href="#">New Admin</a></li>
					</ul>
				</div>
			</li>
			<li>
				<div class="dropdown">
					<button class="btn btn-primary dropdown-toggle" id="menu1" type="button" data-toggle="dropdown">Group
						<span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
						<li role="presentation">
              <a role="menuitem" tabindex="-1" href="<%= new_admin_user_group_url %>">User, Group Subscribe</a>
            </li>
						<li role="presentation">
              <a role="menuitem" tabindex="-1" href="#">User, Group Un-subscribe</a>
            </li>
					</ul>
				</div>
			</li>
    </ul>
	</div>
	<table class = "table table-hover">
		<caption> Browse Files </caption>
		<thead>
			<tr>
				<th> File Name </th>
				<th> Uploaded By </th>
				<th> Size (B) </th>
				<th> Group Name </th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td> ABC </td>
				<td> ATHI </td>
				<td> 1024 </td>
				<td> XYZ </td>
			</tr>
		</tbody>
	</table>
</div>

app/views/layouts/_folders.html.erb
<div class = "col-md-2 col-md-offset-1">
	<h1> Folders </h1>
  <% cf = current_folder %>

  <% if cf.nil? %>
    <p> No folders present </p>
  <% else %>
    <ul>
      <% cf.current_directory.each do |folder| %>
        <%= folder.folder_name.to_s %>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class = "footer navbar navbar-fixed-bottom fileio-color">
	<div class = "container">
		<nav>
			<ul>
				<li> <%= link_to "Contact", "mailto:RUBAN.ATHI@GMAIL.COM", class: "navbar-custom" %> </li>
				<li> <%= link_to "BitBucket", "#", class: "navbar-custom" %> </li>
			</ul>
		</nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top fileio-color">
	<div class = "container">	
		<%= link_to "fileio", root_url, id: "logo" %>
		<nav>
		<!-- There are three types of users : admin, default, manager/end user -->
			<ul class = "nav navbar-nav navbar-right">
				<li> <%= link_to "Home", root_url, class: "navbar-custom" %> </li>
			<% unless is_logged_in? %>
				<li> <%= link_to "Features", "#", class: "navbar-custom" %> </li>
				<li> <%= link_to "Demo", demo_path, class: "navbar-custom" %> </li>
				<li> <%= link_to "About", about_path, class: "navbar-custom" %> </li>
			<% else %>
				<li class = "dropdown"> 
					<a href = "#" class = "dropdown-toggle navbar-custom" data-toggle = "dropdown">
					  Account <b class = "caret"></b>
					</a>
					<ul class = "dropdown-menu">
					  <li> <%= link_to "Profile", '#', class: "navbar-custom" %> </li>
					  <li> <%= link_to "Settings", '#', class: "navbar-custom" %> </li>
					  <li class = "divider"></li>
					  <li> <%= link_to "Logout", logout_path, class: "navbar-custom" %> </li>
					</ul>
				</li>
			<% end %> 
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Fileio</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'shared/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>